# Travis-CI Build for koreader
# see travis-ci.org for details

language: c

compiler:
    - gcc

env:
    - EMULATE_READER=1 USE_NO_CCACHE=1

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install libsdl1.2-dev luarocks nasm
    - sudo luarocks install busted
    - sudo luarocks install luacov
    - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script:
    - make fetchthirdparty all
    - sudo cp base/build/*/luajit /usr/bin/
    - sudo ln -sf /usr/bin/luajit /usr/bin/lua
    - make testfront

after_success:
    - make coverage
    - cd koreader-*/koreader && luacov-coveralls -v
